// <auto-generated />
using System;
using Bilheteria.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bilheteria.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.FilmeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassificacaoIndicativa")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("c_classificacao_indicativa");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_duracao_minutos");

                    b.Property<bool>("EmCartaz")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("c_em_cartaz");

                    b.Property<string>("Genero")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("c_genero");

                    b.Property<string>("Sinopse")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("c_sinopse");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("c_titulo");

                    b.HasKey("Id");

                    b.ToTable("tb_filme");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.IngressoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fileira")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("c_fileira");

                    b.Property<int>("NumeroAssento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_numero_assento");

                    b.Property<int>("PedidoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_pedido_id");

                    b.Property<decimal>("PrecoPago")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("c_preco_pago");

                    b.Property<int>("SessaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_sessao_id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex(new[] { "SessaoId", "Fileira", "NumeroAssento" }, "IDX_ASSENTO_SESSAO")
                        .IsUnique();

                    b.ToTable("tb_ingresso");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.ItemPedidoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_pedido_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("c_preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_quantidade");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("c_subtotal");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("PedidoId", "ProdutoId");

                    b.ToTable("tb_item_pedido");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.PedidoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraPedido")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("c_data_hora_pedido");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("c_nome_cliente");

                    b.Property<int>("SessaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_sessao_id");

                    b.Property<string>("StatusPedido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("c_status_pedido");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("c_valor_total");

                    b.HasKey("Id");

                    b.HasIndex("DataHoraPedido");

                    b.HasIndex("SessaoId");

                    b.ToTable("tb_pedido");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.ProdutoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("c_categoria");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("c_nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("c_preco");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_quantidade_estoque");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.ToTable("tb_produto");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.SessaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadeTotal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_capacidade_total");

                    b.Property<DateTime>("DataHoraSessao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("c_data_hora_sessao");

                    b.Property<int>("FilmeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_filme_id");

                    b.Property<decimal>("PrecoIngresso")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("c_preco_ingresso");

                    b.Property<string>("Sala")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("c_sala");

                    b.HasKey("Id");

                    b.HasIndex("FilmeId", "DataHoraSessao");

                    b.ToTable("tb_sessao");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.IngressoEntity", b =>
                {
                    b.HasOne("Bilheteria.API.Domain.Entities.PedidoEntity", "Pedido")
                        .WithMany("Ingressos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bilheteria.API.Domain.Entities.SessaoEntity", "Sessao")
                        .WithMany("Ingressos")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.ItemPedidoEntity", b =>
                {
                    b.HasOne("Bilheteria.API.Domain.Entities.PedidoEntity", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bilheteria.API.Domain.Entities.ProdutoEntity", "Produto")
                        .WithMany("ItensPedido")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.PedidoEntity", b =>
                {
                    b.HasOne("Bilheteria.API.Domain.Entities.SessaoEntity", "Sessao")
                        .WithMany("Pedidos")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.SessaoEntity", b =>
                {
                    b.HasOne("Bilheteria.API.Domain.Entities.FilmeEntity", "Filme")
                        .WithMany("Sessoes")
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.FilmeEntity", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.PedidoEntity", b =>
                {
                    b.Navigation("Ingressos");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.ProdutoEntity", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("Bilheteria.API.Domain.Entities.SessaoEntity", b =>
                {
                    b.Navigation("Ingressos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
